/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


public class Registros_frame extends javax.swing.JFrame {

    /**
     * Creates new form Registros_frame
     */
    public Registros_frame() {
    	getContentPane().setBackground(Color.GRAY);
        initComponents();
        setSize(949, 577);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_registros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_buscar_funcionario = new javax.swing.JTextField();
        btn_buscar_funcionario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_registros1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_buscar_fecha = new javax.swing.JTextField();
        btn_buscar_fecha = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buscador = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_buscar_servicio = new javax.swing.JTextField();
        btn_buscar_servicio = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Servicio", "Funcionario", "Codigo", "Marca", "Linea", "Año", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_registros.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(table_registros);
        table_registros.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table_registros.getColumnModel().getColumnCount() > 0) {
            table_registros.getColumnModel().getColumn(0).setPreferredWidth(30);
            table_registros.getColumnModel().getColumn(2).setPreferredWidth(70);
            table_registros.getColumnModel().getColumn(3).setPreferredWidth(30);
            table_registros.getColumnModel().getColumn(4).setPreferredWidth(30);
            table_registros.getColumnModel().getColumn(5).setPreferredWidth(30);
            table_registros.getColumnModel().getColumn(6).setPreferredWidth(30);
            table_registros.getColumnModel().getColumn(7).setPreferredWidth(25);
        }

        jLabel1.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel1.setText("Registros");

        jLabel2.setText("Buscar por funcionario: ");

        txt_buscar_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_funcionarioActionPerformed(evt);
            }
        });
        txt_buscar_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar_funcionarioKeyTyped(evt);
            }
        });

        btn_buscar_funcionario.setText("Buscar");

        table_registros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Servicio", "Funcionario", "Codigo", "Marca", "Linea", "Añoo", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_registros1);
        table_registros1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table_registros1.getColumnModel().getColumnCount() > 0) {
            table_registros1.getColumnModel().getColumn(0).setPreferredWidth(30);
            table_registros1.getColumnModel().getColumn(2).setPreferredWidth(70);
            table_registros1.getColumnModel().getColumn(3).setPreferredWidth(30);
            table_registros1.getColumnModel().getColumn(4).setPreferredWidth(30);
            table_registros1.getColumnModel().getColumn(5).setPreferredWidth(30);
            table_registros1.getColumnModel().getColumn(6).setPreferredWidth(30);
            table_registros1.getColumnModel().getColumn(7).setPreferredWidth(25);
        }

        jLabel3.setText("Buscar por fecha: ");

        txt_buscar_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_fechaActionPerformed(evt);
            }
        });
        txt_buscar_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar_fechaKeyTyped(evt);
            }
        });

        btn_buscar_fecha.setText("Buscar");

        jLabel4.setText("Buscando");

        buscador.setText("...");

        jLabel5.setText("Buscar por servicio: ");

        txt_buscar_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_servicioActionPerformed(evt);
            }
        });
        txt_buscar_servicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar_servicioKeyTyped(evt);
            }
        });

        btn_buscar_servicio.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(442)
        			.addComponent(jLabel1)
        			.addContainerGap(447, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(34, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 888, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 888, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(155)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(buscador, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        							.addGap(105)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel2)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(txt_buscar_funcionario, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE))
        								.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        									.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(jLabel5)
        										.addComponent(jLabel3))
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(txt_buscar_fecha, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(btn_buscar_fecha)
        								.addComponent(btn_buscar_funcionario)))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txt_buscar_servicio, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(btn_buscar_servicio)))))
        			.addGap(27))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(30)
        			.addComponent(jLabel1)
        			.addGap(30)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txt_buscar_funcionario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(btn_buscar_funcionario))
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel2)
        					.addComponent(jLabel4)
        					.addComponent(buscador)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btn_buscar_fecha)
        				.addComponent(txt_buscar_fecha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btn_buscar_servicio)
        				.addComponent(txt_buscar_servicio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        			.addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
        			.addGap(14))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscar_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_funcionarioKeyTyped

    }//GEN-LAST:event_txt_buscar_funcionarioKeyTyped

    private void txt_buscar_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_funcionarioActionPerformed

    private void txt_buscar_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_fechaActionPerformed

    private void txt_buscar_fechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_fechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_fechaKeyTyped

    private void txt_buscar_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_servicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_servicioActionPerformed

    private void txt_buscar_servicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_servicioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_servicioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_buscar_fecha;
    public javax.swing.JButton btn_buscar_funcionario;
    public javax.swing.JButton btn_buscar_servicio;
    public javax.swing.JLabel buscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable table_registros;
    public javax.swing.JTable table_registros1;
    public javax.swing.JTextField txt_buscar_fecha;
    public javax.swing.JTextField txt_buscar_funcionario;
    public javax.swing.JTextField txt_buscar_servicio;
    // End of variables declaration//GEN-END:variables
}
