/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;


public class Servicios_frame extends javax.swing.JFrame {

    /**
     * Creates new form Servicios_frame
     */
    public Servicios_frame() {
        initComponents();
        setTitle("Servicios");
        setResizable(false);
        setLocationRelativeTo(this);
        setSize(601, 557);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnAceptarPeticion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAgnio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        comboBoxTipo = new javax.swing.JComboBox<>();
        comboBox_servicio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel1.setText("Servicios");

        jLabel2.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel2.setText("Linea:");

        jLabel3.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel3.setText("Informacion del Auto:");

        jLabel4.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel4.setText("Marca:");

        jLabel5.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel5.setText("Tipo:");

        txtLinea.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineaActionPerformed(evt);
            }
        });

        txtMarca.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        btnAceptarPeticion.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        btnAceptarPeticion.setText("Aceptar");
        btnAceptarPeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPeticionActionPerformed(evt);
            }
        });

        jLabel6.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel6.setText("A\u00F1o:");

        txtAgnio.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtAgnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgnioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        jLabel7.setText("Codigo:");

        txtCodigo.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camioneta" }));

        comboBox_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lavado basico", "Lavado especial", "Desinfeccion basica", "Desinfeccion avanzada", "Combo 1", "Combo 2", "Combo 3" }));
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(230)
        					.addComponent(jLabel1))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(64)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(comboBox_servicio, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        								.addGroup(groupLayout.createSequentialGroup()
        									.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        									.addGap(20)
        									.addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
        								.addGroup(groupLayout.createSequentialGroup()
        									.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(txtAgnio, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(comboBoxTipo, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        								.addComponent(txtLinea, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))))))
        			.addGap(46))
        		.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        			.addContainerGap(191, Short.MAX_VALUE)
        			.addComponent(btnAceptarPeticion, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
        			.addGap(179))
        		.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        			.addContainerGap(171, Short.MAX_VALUE)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
        			.addGap(146))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap(40, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(58)
        			.addComponent(jLabel3)
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(5)
        					.addComponent(jLabel4))
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel2)
        					.addComponent(txtLinea, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(24)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        					.addComponent(jLabel6)
        					.addComponent(txtAgnio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(comboBoxTipo, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel5)))
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(98)
        					.addComponent(btnAceptarPeticion, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(33)
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel7)
        						.addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(comboBox_servicio, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))))
        			.addGap(42))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineaActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtAgnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgnioActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnAceptarPeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPeticionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarPeticionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarPeticion;
    public javax.swing.JComboBox<String> comboBoxTipo;
    public javax.swing.JComboBox<String> comboBox_servicio;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txtAgnio;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtLinea;
    public javax.swing.JTextField txtMarca;
    // End of variables declaration//GEN-END:variables
}
